name: Teste MSYS2
on:
  - push
  - pull_request
permissions: {}
jobs:
  CI:
    permissions:
      contents: write # for npx prebuild to make release
    name: ${{ matrix.container || matrix.os }} - Node.js ${{ matrix.nodejs_version }} ${{ matrix.nodejs_arch }} ${{ matrix.prebuild && '- prebuild' }}
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            nodejs_version: 18
            nodejs_arch: x64
    steps:
      - name: Install mingw-w64-ucrt-x86_64-glib2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
      - shell: msys2 {0}
        run: pacman --noconfirm -S mingw-w64-ucrt-x86_64-glib2

      - name: List C:\msys64\ucrt64\bin contents
        run: |
          Get-ChildItem C:\msys64\ucrt64\bin
